# Site settings
title: Davide Vanzo
description: 'Auream quisquis mediocritatem diligit, tutus caret obsoleti sordibus tecti, caret invidenda sobrius aula.'
url: 'http://vanzod.github.io'
baseurl: '/'

author:
  name: 'Davide Vanzo'
#  email: 
#  twitter_username:
#  facebook_username:
  github_username:  vanzod
  linkedin_username:  vanzodavide

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
